/**
 * ui-strings.ts — Phase 1 UI 字串常數（stub 供舊 shell.ts / guild-hall-scene.ts 引用）
 *
 * Phase 2 不再使用這些字串（shell.ts / guild-hall-scene.ts 為 dead code）。
 * 此 stub 僅讓 tsc 通過。
 */

export const UI_STRINGS = {
  // Phase 2 使用的 keys
  gold: '金幣',
  reputation: '聲望',
  missionBoard: '委託板',
  adventurerHall: '冒險者名冊',
  dispatch: '派遣',
  recommend: '推薦',
  pending: '待審',
  active: '進行中',
  completed: '已完成',
  outcome: {
    SUCCESS:  '成功',
    PYRRHIC:  '慘勝',
    FAILURE:  '失敗',
    DEATH:    '死亡',
  },

  // Phase 1 dead code stubs（shell.ts / guild-hall-scene.ts 引用）
  loadingText: '',
  hallLoading: '',
  statusGold: '',
  statusBankruptWarn: '',
  statusDebt: '',
  statusPending: '',
  statusReputation: '',
  hallOffice: '',
  hallGuildMaster: '',
  hallDesk: '',
  hallReception: '',
  hallReceptionCounter: '',
  hallBackDoor: '',
  hallQuestBoard: '',
  commissionEmpty: '',
  commissionCardClose: '',
  commissionPanelTitle: '',
  rosterEmpty: '',
  rosterPanelTitle: '',
  rosterSelected: '',
  rosterStatusAvailable: '',
  rosterStatusOnMission: '',
  adventurerDead: '',
  toolbarSave: '',
  toolbarExport: '',
  toolbarImport: '',
  reviewTitle: '',
  reviewEmpty: '',
  reviewAccept: '',
  reviewReject: '',
  recommendTitle: '',
  recommendMissionsTitle: '',
  recommendMissionsEmpty: '',
  recommendRosterEmpty: '',
  recommendButton: '',
  hallConstructionTitle: '',
  hallConstructionPlaceholder: '',
  guildMasterTitle: '',
  guildMasterRosterTitle: '',
  guildMasterFireButton: '',
  guildMasterCandidatesTitle: '',
  recruitNoCandidates: '',
  guildMasterRecruitButton: '',
  settlementTitle: '',
  settlementLongOffline: '',
  settlementConfirm: '',
  settlementSuccess: '',
  settlementFail: '',
  settlementDeath: '',
  settlementPyrrhic: '',
} as const
